"use client";

import { useFrame } from "@react-three/fiber";
import { useLayoutEffect, useMemo, useRef } from "react";
import * as THREE from "three";
const dummy = new THREE.Object3D();
function matrixGrid(cols: number, rows: number, spacingX: number, spacingZ: number, origin: readonly [number, number, number], tilt = 0) { const result: THREE.Matrix4[] = []; for (let row=0; row<rows; row+=1) for (let col=0; col<cols; col+=1) { dummy.position.set(origin[0]+(col-(cols-1)/2)*spacingX, origin[1], origin[2]+row*spacingZ); dummy.rotation.set(tilt,0,0); dummy.scale.set(1,1,1); dummy.updateMatrix(); result.push(dummy.matrix.clone()); } return result; }
export function R6InstancedSolarField({ compact=false }: { compact?: boolean }) { const ref=useRef<THREE.InstancedMesh>(null); const frame=useRef<THREE.InstancedMesh>(null); const matrices=useMemo(()=>matrixGrid(compact?10:18,compact?3:5,0.82,0.72,[-1.4,0.08,-4.2],-0.28),[compact]); useLayoutEffect(()=>{ for(const mesh of [ref.current,frame.current]){ if(!mesh) continue; matrices.forEach((matrix,index)=>mesh.setMatrixAt(index,matrix)); mesh.instanceMatrix.needsUpdate=true; mesh.computeBoundingSphere(); } },[matrices]); return <group><instancedMesh ref={frame} args={[undefined,undefined,matrices.length]} castShadow receiveShadow><boxGeometry args={[0.69,0.055,0.49]} /><meshStandardMaterial name="SolarFrame" color="#6f797a" metalness={0.82} roughness={0.27} /></instancedMesh><instancedMesh ref={ref} args={[undefined,undefined,matrices.length]} castShadow receiveShadow><boxGeometry args={[0.63,0.035,0.43]} /><meshStandardMaterial name="SolarGlass" color="#17364f" metalness={0.45} roughness={0.16} /></instancedMesh></group>; }
export function R6InstancedTurbines({ count=2, quality="high" }: { count?: number; quality?: "high"|"medium" }) { const towers=useRef<THREE.InstancedMesh>(null); const hubs=useRef<THREE.InstancedMesh>(null); const bladeGroups=useRef<Array<THREE.Group|null>>([]); const positions=useMemo(()=>Array.from({length:count},(_,i)=>new THREE.Vector3(3.2+i*2.3,1.9,-4.2+(i%2)*0.7)),[count]); useLayoutEffect(()=>{ positions.forEach((p,i)=>{ dummy.position.copy(p); dummy.rotation.set(0,0,0); dummy.scale.set(1,1,1); dummy.updateMatrix(); towers.current?.setMatrixAt(i,dummy.matrix); dummy.position.set(p.x,p.y+1.75,p.z); dummy.updateMatrix(); hubs.current?.setMatrixAt(i,dummy.matrix); }); if(towers.current) towers.current.instanceMatrix.needsUpdate=true; if(hubs.current) hubs.current.instanceMatrix.needsUpdate=true; },[positions]); useFrame((state)=>{ const angle=state.clock.elapsedTime*0.23; bladeGroups.current.forEach((group,i)=>{ if(group) group.rotation.z=angle+i*0.7; }); }); return <group><instancedMesh ref={towers} args={[undefined,undefined,count]} castShadow><cylinderGeometry args={[0.08,0.16,3.5,16]} /><meshStandardMaterial color="#e8e8e1" roughness={0.48} metalness={0.12} /></instancedMesh><instancedMesh ref={hubs} args={[undefined,undefined,count]} castShadow><sphereGeometry args={[0.14,16,12]} /><meshStandardMaterial color="#f1f0e9" roughness={0.42} metalness={0.1} /></instancedMesh>{positions.map((p,i)=><group key={i} ref={(node)=>{bladeGroups.current[i]=node;}} position={[p.x,p.y+1.75,p.z+0.01]}>{[0,1,2].map((blade)=><group key={blade} rotation={[0,0,blade*Math.PI*2/3]}><mesh position={[0,0.71,0]} castShadow={quality==="high"}><boxGeometry args={[0.075,1.42,0.035]} /><meshStandardMaterial color="#f3f1e9" roughness={0.48} /></mesh></group>)}</group>)}</group>; }
export function R6InstancedVegetation({ count=16 }: { count?: number }) { const trunks=useRef<THREE.InstancedMesh>(null); const crowns=useRef<THREE.InstancedMesh>(null); const positions=useMemo(()=>Array.from({length:count},(_,i)=>{ const side=i%2===0?-1:1; return new THREE.Vector3(-5.8+(i%8)*1.55,0.34,side*4.35+(i%3)*0.12); }),[count]); useLayoutEffect(()=>{ positions.forEach((p,i)=>{ dummy.position.set(p.x,p.y-0.10,p.z); dummy.scale.set(1,1,1); dummy.updateMatrix(); trunks.current?.setMatrixAt(i,dummy.matrix); dummy.position.set(p.x,p.y+0.35,p.z); dummy.scale.set(0.8+(i%3)*0.09,0.8+(i%4)*0.08,0.8); dummy.updateMatrix(); crowns.current?.setMatrixAt(i,dummy.matrix); }); if(trunks.current) trunks.current.instanceMatrix.needsUpdate=true; if(crowns.current) crowns.current.instanceMatrix.needsUpdate=true; },[positions]); return <group><instancedMesh ref={trunks} args={[undefined,undefined,count]} castShadow><cylinderGeometry args={[0.045,0.07,0.7,8]} /><meshStandardMaterial color="#76543a" roughness={0.95} /></instancedMesh><instancedMesh ref={crowns} args={[undefined,undefined,count]} castShadow><icosahedronGeometry args={[0.32,1]} /><meshStandardMaterial color="#486b49" roughness={0.92} /></instancedMesh></group>; }
